### ISSUE TITLE
[Client] 주요기능 구현 - Change Background

### ISSUE THREAD

**Issue by kavoom2** [codestates/BuildUp-client#12]
## Fill the title according to the below form
[Client/Server/Database] / [#이슈번호] / edit: [수정한 파일명]

## ISSUE
* Group: client
* Type: add
* Detail: add change background system

## TODO
- [x] Weather API에서 날씨 정보를 가져오는 GET 기능 구현
- [x] 가져온 날씨 정보를 협의한 기준에 따라 Filtering하는 기능 구현
- [ ] 필터링한 정보를 서버에 전달하여 특정 Wallpaper의 URL 또는 File을 가져오는 기능 구현

## Estimated time
> Pick one of the below
> 3h

## Labels
Estimated time: E: 3h
Group : client
Sprint: Sprint2
Urgency: Middle
