### ISSUE TITLE
[Client] 주요기능 구현 - 모달창, TODO CRUD

### ISSUE THREAD

**Issue by kavoom2** [codestates/BuildUp-client#15]
## Fill the title according to the below form
[Client/Server/Database] / [#이슈번호] / edit: [수정한 파일명]

## ISSUE
* Group: client
* Type: add
* Detail: add change background system

## TODO
- [x] 모달창 컴포넌트 구현
- [x] TODO List CRUD 기능 구현
- [x] 모달창 슬라이드 효과

## Estimated time
> Pick one of the below
> 3h

## Labels
Estimated time: E: 3h
Group : client
Sprint: Sprint2
Urgency: Middle
