### ISSUE TITLE
[Client] 부수기능 구현 - Main page Carousel(React + Vanilla JS)

### ISSUE THREAD

**Issue by kavoom2** [codestates/BuildUp-client#16]
## Fill the title according to the below form
[Client/Server/Database] / [#이슈번호] / edit: [수정한 파일명]

## ISSUE
* Group: client
* Type: add
* Detail: add main page carousel effect

## TODO
- [x] Carousel 인터페이스 (버튼 / 하단 위치 네비게이터)
- [x] Carousel 기능 구현
- [x] 슬라이더 효과 구현
- [x] 인피니트 스크롤 효과 구현

## Estimated time
> Pick one of the below
> 3h

## Labels
Estimated time: E: 3h
Group : client
Sprint: Sprint2
Urgency: Low
