### ISSUE TITLE
[Guide] 임시 서버 및 더미데이터 Repo 주소입니다.

### ISSUE THREAD

**Issue by kavoom2** [codestates/BuildUp-client#19]
## 임시서버 및 데이터베이스 Repo
POST맨으로 각 Endpoint에서 Req.header, Req.body, Res.data의 결과가 적합한 것을 확인 후 게시합니다.    
서버 주소는 **http://localhost:4000** 으로 사용하며, Client에는 .env를 만드세요.
    
Repo 주소: **https://github.com/kavoom2/temp-server-for-token**

## ISSUE
* Group: server
* Type: add
* Detail: add temp server

## TODO
- [x] CORS셋팅 및 Token 기반 로그인, 로그아웃, 회원가입 통신 가능
- [x] 엔드포인트 todo/info로 더미데이터 (약 100개) 수신 가능
- [ ] todo 나머지 엔드포인트 및 picture 구현

## Estimated time
> Pick one of the below
> 0.5h

## Labels
Estimated time: E: 0.5h
Group : server
Sprint: Sprint2
Urgency: Low
