### ISSUE TITLE
[Client] 시스템 아키텍쳐 설계

### ISSUE THREAD

**Issue by kavoom2** [codestates/BuildUp-client#2]
## Fill the title according to the below form
[Client/Server/Database] / [#이슈번호] / edit: [수정한 파일명]

## ISSUE
* Group: client
* Type: 계획
* Detail: 클라이언트 기능 플로우 및 와이어프레임 설계

## TODO
- [x] 각 페이지 구성 및 기능플로우 작성
- [x] 메인 페이지 와이어 프레임 작성
- [x] 마이 페이지 와이어 프레임 작성
- [x] 회원가입 페이지 와이어 프레임 작성
- [x] Todo list 페이지 와이어 프레임 작성

## Estimated time
3h

## Labels
Estimated time: E: 3h
Group : client
Sprint: Sprint 1
Urgency: High
