### ISSUE TITLE
[Client] Node.js 필수 패키지 설치 및 설정

### ISSUE THREAD

**Issue by kavoom2** [codestates/BuildUp-client#4]
## Fill the title according to the below form
[Client/Server/Database] / [#이슈번호] / edit: [수정한 파일명]

## ISSUE
* Group: client
* Type: add
* Detail: 프로젝트 Node.js 필수 패키지 설치

## TODO
- [x] .env 파일 생성 및 개발/배포 환경 설정
- [x] .gitignore 파일 생성 및 설정
- [x] ESlint, Prettier 설치 및 기본설정
- [x] React Hooks, Redux 패키지 설치

## Estimated time
> Pick one of the below
>1.5h

## Labels
Estimated time: E: 1.5h
Group : client
Sprint: Sprint 2
Urgency: Low
