### ISSUE TITLE
[Client] CSS 레이아웃 및 스타일링

### ISSUE THREAD

**Issue by kavoom2** [codestates/BuildUp-client#52]
## Fill the title according to the below form
[Client/Server/Database] / [#이슈번호] / edit: [수정한 파일명]

## ISSUE
* Group: client, server, database
* Type: add, fix, delete
* Detail: fix actions from group

## TODO
- [x] CSS 레이아웃 배치
- [x] 컬러팔레트 설정 및 요소 스타일링
- [x] CSS Transition 효과 

## Estimated time
> Pick one of the below
>  3h

## Labels
Estimated time: E: 3h
Group : client
Sprint: Sprint2
Urgency: Middle
